{% set name = "PyMonCtl" %}
{% set version = "0.92" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Kalmat/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 64170278da9301071e724a25d687c1de2ca14b2b11bfc6027eec49384d564275

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]
    - pywin32 >=302  # [win]
    - python-xlib >=0.21  # [linux]
    - ewmhlib >=0.1  # [linux]
    - pyobjc-framework-cocoa >=8.1  # [osx]
    - pyobjc-framework-quartz >=8.1  # [osx]
    - typing_extensions >=4.4.0

test:
  requires:
    - python {{ python_min }}
  commands:
    - "DISPLAY=localhost:1.0 XDG_SESSION_TYPE=x11 xvfb-run -a python -c 'import pymonctl'"  # [linux]
  imports:
    - pymonctl  # [not linux] pywinbox fails on import as no display is available

about:
  home: https://github.com/Kalmat/PyMonCtl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Cross-Platform toolkit to get info on and control monitors connected'
  dev_url: https://github.com/Kalmat/PyMonCtl

extra:
  recipe-maintainers:
    - '0xbe7a'
